---
# Handle directory creation

- name: Ensure backup directory exists
  file:
    path: "{{ mneme_backup_dir }}"
    state: directory
    owner: "{{ mneme_backup_script_owner }}"
    group: "{{ mneme_backup_script_group }}"
    mode: '0755'

- name: Ensure log directory exists
  file:
    path: "{{ mneme_log_dir }}"
    state: directory
    owner: "{{ mneme_backup_script_owner }}"
    group: "{{ mneme_backup_script_group }}"
    mode: '0755'

- name: Ensure temp directory exists
  file:
    path: "{{ mneme_temp_dir }}"
    state: directory
    owner: "{{ mneme_backup_script_owner }}"
    group: "{{ mneme_backup_script_group }}"
    mode: '0755'

- name: Ensure archive directory exists
  file:
    path: "{{ mneme_archive_dir }}"
    state: directory
    owner: "{{ mneme_backup_script_owner }}"
    group: "{{ mneme_backup_script_group }}"
    mode: '0755' 