---
# Handle package installation

- name: Install mariadb-backup on RHEL/CentOS/OL
  ansible.builtin.yum:
    name: MariaDB-backup
    state: present
  when: not mneme_xtrabackup_compatibility
  register: mneme_install_result
  retries: 3
  delay: 5
  until: mneme_install_result is succeeded
  failed_when: 
    - mneme_install_result is failed
    - not mneme_xtrabackup_compatibility
  ignore_errors: "{{ mneme_xtrabackup_compatibility }}"

- name: Install pigz (parallel version of gzip)
  ansible.builtin.yum:
    name: pigz
    state: present
  register: pigz_install_result
  retries: 3
  delay: 5
  until: pigz_install_result is succeeded
  failed_when: pigz_install_result is failed
  ignore_errors: false

- name: Ensure cronie for crontab is installed
  ansible.builtin.yum:
    name: cronie
    state: present
  register: cronie_install_result
  retries: 3
  delay: 5
  until: cronie_install_result is succeeded
  failed_when: cronie_install_result is failed
  ignore_errors: false

- name: Verify MariaDB backup binary exists
  ansible.builtin.stat:
    path: "{{ mneme_bin_path }}"
  register: mneme_bin_stat
  failed_when: 
    - not mneme_bin_stat.stat.exists
    - not mneme_xtrabackup_compatibility
  ignore_errors: "{{ mneme_xtrabackup_compatibility }}"
  when: not mneme_xtrabackup_compatibility 