---
# Handle directory creation

- name: Create directories without metadata
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ mneme_backup_dir }}"
    - "{{ mneme_log_dir }}"
    - "{{ mneme_temp_dir }}"
    - "{{ mneme_archive_dir }}"

- name: Try to set permissions (can fail on network shares)
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ mneme_backup_script_owner }}"
    group: "{{ mneme_backup_script_group }}"
    mode: '0755'
  loop:
    - "{{ mneme_backup_dir }}"
    - "{{ mneme_log_dir }}"
    - "{{ mneme_temp_dir }}"
    - "{{ mneme_archive_dir }}"
  ignore_errors: true